spring:
  datasource:
    url: jdbc:mysql://<prod-url>:3306/proddb
    username: prod_user
    password: prod_password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: ERROR
custom:
